version: '3.8'

x-airflow-common: &airflow-common
  build: .
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-metadata/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
  volumes:
    - .:/opt/airflow
  depends_on:
    airflow-metadata:
      condition: service_healthy

services:
  # YOUR EXISTING DATA WAREHOUSE (Renamed so internal network can find it)
  data-warehouse:
    image: postgres:15
    environment:
      - POSTGRES_USER=dwh_admin
      - POSTGRES_PASSWORD=dwh_password
      - POSTGRES_DB=retailco_dwh
    ports:
      - "5434:5432"

  # AIRFLOW METADATA DATABASE (A separate isolated DB just for Airflow to track task history)
  airflow-metadata:
    image: postgres:15
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  # AIRFLOW SERVICES
  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db migrate && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always