retailco_models:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: data-warehouse
      port: 5432
      user: dwh_admin
      pass: dwh_password
      dbname: retailco_dwh
      schema: public
  target: dev
