with source as (
    select * from {{ ref('customer_snapshot') }}
)

select
    -- dlt usually creates snake_case automatically, but we explicitly cast types here
    cast(id as varchar) as customer_id,
    cast(first_name as varchar) as first_name,
    cast(last_name as varchar) as last_name,
    cast(email as varchar) as email,
    cast(segment as varchar) as customer_segment,
    cast(address as varchar) as address,
    
    -- SCD2 Columns generated by our snapshot
    dbt_valid_from as valid_from,
    dbt_valid_to as valid_to,
    case when dbt_valid_to is null then true else false end as is_current,
    
    -- We keep is_deleted here as per the brief ("Keep them in SCD2 dimension snapshots")
    cast(is_deleted as boolean) as is_deleted

from source