version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_sk
        tests:
          - unique
          - not_null

  - name: dim_product
    columns:
      - name: product_sk
        tests:
          - unique
          - not_null

  - name: fct_sales
    columns:
      - name: sales_sk
        tests:
          - unique
          - not_null
      - name: customer_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_sk

  - name: fct_payments
    columns:
      - name: payment_sk
        tests:
          - unique
          - not_null
      - name: payment_method_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_payment_method')
              field: payment_method_sk